### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Jesusxsmn**
I changed the map stuff to show where the actual wedding will be I'm just working on getting it to publish

### CODE REVIEW

**Comment by paulserraino** [comment]
wow badass! :+1:

**Comment by paulserraino** [comment]
The only thing left, is getting the rsvp form working. There was a change in the
api, I'll try and update it during lunch

**Comment by Jesusxsmn** [comment]
tight man anything I can help with?

**Comment by paulserraino** [comment]
fosho, what do you think of this RSVP form http://anya-demo.squarespace.com/rsvp-anya ? I'm planing on totally ripping it off (css and everything). 

If you like, try and add the form fields to the existing form and i'll patch it all together.

here's an example.
```html
<div class="form-group">
  <label>Will you be there? *</label>
  <input type="text" class="form-control">
</div>
```

**Pull request merged**
